apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox3
  namespace: dev
  labels:
    app: busybox3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox3
  template:
    metadata:
      labels:
        app: busybox3
    spec:
      containers:
      - name: busybox-container
        image: busybox:latest
        # Keep the container running
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources:
          requests:
            cpu: 30m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
